"""Optional deterministic bundle over the existing replay, release and verifier."""
from __future__ import annotations

from datetime import datetime
import hashlib
import json
import re
from .bundle_primitives import build_prompt_package, record_benchmark, _redact
from .bundle_verification import verify_release_bundle
from .judgment import _bounded, _object
from .ops import OpsValidationError, release_manifest

MAX_BUNDLE_INPUT = 2 * 1024 * 1024
MAX_SOURCE_INPUT = 8 * 1024 * 1024
MAX_EXPORT = 64 * 1024 * 1024
MAX_NODES = 250_000
ALGORITHM = 'source-sha256-pair-v1'
SHA = re.compile(r'[0-9a-f]{64}\Z')


def _finite_tree(value, maximum=MAX_SOURCE_INPUT):
    """Bound structural depth before serializers or recursive schema tests."""
    stack=[(value,0)];nodes=0
    while stack:
        item,depth=stack.pop();nodes+=1
        if depth>20 or nodes>MAX_NODES:
            raise OpsValidationError('bundle JSON structure exceeds its limit')
        if type(item) is dict:
            if any(type(k) is not str for k in item):raise OpsValidationError('bundle JSON keys must be strings')
            stack.extend((x,depth+1) for x in item.values())
        elif type(item) is list:stack.extend((x,depth+1) for x in item)
        elif type(item) not in (str,int,float,bool,type(None)):
            raise OpsValidationError('bundle requires plain finite JSON')
    _bounded(value,maximum)


def refuse_sensitive(value, *, trusted_values=None, trusted_keys=()):
    """Pattern policy, not complete secret detection; never returns raw material.

    Only exact paths AND values validated/generated by the native caller can
    bypass an entropy false positive. A user-chosen field name grants nothing.
    """
    _finite_tree(value,MAX_EXPORT)
    trusted_values=trusted_values or {}
    stack=[((),value,False)]
    while stack:
        path,item,is_key=stack.pop()
        if isinstance(item,dict):
            for name,child in item.items():
                stack.append(((*path,name),name,True));stack.append(((*path,name),child,False))
        elif isinstance(item,list):stack.extend(((*path,index),child,False) for index,child in enumerate(item))
        elif isinstance(item,str):
            if is_key and path in trusted_keys:continue
            if not is_key and path in trusted_values and item==trusted_values[path]:continue
            if _redact(item)[1]:
                raise OpsValidationError('bundle export refused: sensitive-looking source material; pattern detection is not exhaustive')


def split_rows(items, *, test_percent=20):
    """Exact historical pair hashing/dedup/split; no seed or model evaluation."""
    _finite_tree(items)
    if not isinstance(items,list) or not 1<=len(items)<=10000 or type(test_percent) is not int or not 1<=test_percent<=99:
        raise OpsValidationError('bounded dataset and integer test_percent required')
    seen=set();rows=[]
    for item in items:
        _object(item,('input','expected'))
        key=hashlib.sha256(json.dumps(item,sort_keys=True,separators=(',',':')).encode()).hexdigest()
        if key in seen:continue
        seen.add(key);rows.append({'id':key,**item,'split':'test' if int(key[:8],16)%100<test_percent else 'train'})
    rows.sort(key=lambda x:x['id'])
    return {'items':rows,'count':len(rows),'sha256':hashlib.sha256(json.dumps(rows,sort_keys=True).encode()).hexdigest()}


def _schema(schema, depth=0):
    if depth>12:raise OpsValidationError('package schema is too deep')
    _object(schema,('type',),('required','properties'))
    kind=schema['type']
    if not isinstance(kind,str) or kind not in {'string','integer','number','boolean','array','object'}:
        raise OpsValidationError('unsupported package schema type')
    if kind!='object' and set(schema)!={'type'}:
        raise OpsValidationError('only object schemas support required/properties')
    if kind=='object':
        required=schema.get('required',[]);props=schema.get('properties',{})
        if not isinstance(required,list) or len(required)>100 or any(not isinstance(x,str) for x in required) or len(set(required))!=len(required):
            raise OpsValidationError('invalid required property names')
        if not isinstance(props,dict) or len(props)>100:raise OpsValidationError('invalid schema properties')
        for child in props.values():_schema(child,depth+1)


def test_package(record):
    """Run source-derived deterministic substitution/schema tests, no model."""
    _finite_tree(record,131072)
    _object(record,('name','version','prompt','variables','output_schema','tests'))
    variables=record['variables']
    if not isinstance(variables,list) or any(not isinstance(x,str) for x in variables):
        raise OpsValidationError('package variables must be strings')
    _schema(record['output_schema'])
    try:return build_prompt_package(record)
    except (TypeError,ValueError,KeyError,OverflowError) as exc:
        raise OpsValidationError('deterministic package test refused: '+str(exc)) from exc


def validate_request(request, suite):
    _finite_tree(request,MAX_BUNDLE_INPUT)
    _object(request,('schema','suite_sha','release_version','split','packages','provenance'))
    if request['schema']!='promptops-bundle-input/1' or request['suite_sha']!=suite.suite_sha:
        raise OpsValidationError('bundle schema or exact suite identity mismatch')
    version=request['release_version']
    from .bundle_primitives import SEMVER
    if not isinstance(version,str) or len(version)>100 or not SEMVER.fullmatch(version):
        raise OpsValidationError('bundle release_version must be bounded strict SemVer')
    split=request['split'];_object(split,('algorithm','test_percent'))
    if split['algorithm']!=ALGORITHM or type(split['test_percent']) is not int or not 1<=split['test_percent']<=99:
        raise OpsValidationError('unsupported split algorithm or test_percent')
    packages=request['packages']
    if not isinstance(packages,list) or len(packages)!=len(suite.candidates):
        raise OpsValidationError('bundle requires one package for every candidate')
    candidates={c.candidate_id:c for c in suite.candidates};seen=set()
    for package in packages:
        _object(package,('candidate_id','record'))
        cid=package['candidate_id']
        if not isinstance(cid,str) or cid not in candidates or cid in seen:
            raise OpsValidationError('unknown or duplicate package candidate')
        seen.add(cid);record=package['record']
        if not isinstance(record,dict) or record.get('prompt')!=candidates[cid].prompt_template or record.get('variables')!=['input']:
            raise OpsValidationError('package must bind exact candidate template and its input variable')
        _finite_tree(record,131072)
        _object(record,('name','version','prompt','variables','output_schema','tests'))
        _schema(record['output_schema'])
    provenance=request['provenance'];_object(provenance,('source_id','declared_at','duration_ms'))
    source_id=provenance['source_id']
    if not isinstance(source_id,str) or not re.fullmatch(r'[a-z0-9][a-z0-9._-]{0,99}',source_id):
        raise OpsValidationError('provenance source_id must be a bounded identifier')
    declared=provenance['declared_at']
    if declared is not None:
        if not isinstance(declared,str) or len(declared)>40:raise OpsValidationError('invalid declared_at')
        try:stamp=datetime.fromisoformat(declared.replace('Z','+00:00'))
        except ValueError as exc:raise OpsValidationError('declared_at must be an offset ISO timestamp or null') from exc
        if stamp.tzinfo is None:raise OpsValidationError('declared_at requires an offset')
    duration=provenance['duration_ms']
    if duration is not None and (type(duration) not in (int,float) or not 0<duration<=86400000):
        raise OpsValidationError('duration_ms must be bounded positive declared milliseconds or null')
    refuse_sensitive(request,trusted_values={('schema',):'promptops-bundle-input/1',('suite_sha',):suite.suite_sha})


def build_bundle(request, suite, values, result, encode):
    """Call native release/verification, then bind deterministic extra artifacts."""
    # Package execution happens once here after contract/source prevalidation.
    package_receipts=[]
    for package in sorted(request['packages'],key=lambda p:p['candidate_id']):
        receipt=test_package(package['record'])
        for case in package['record']['tests']:
            rendered=package['record']['prompt'].replace('{input}',case['variables']['input'])
            if rendered!=case['expected_prompt']:
                raise OpsValidationError('package substitution differs from native replay template rendering')
        package_receipts.append({'candidate_id':package['candidate_id'],'template_sha256':hashlib.sha256(package['record']['prompt'].encode()).hexdigest(),
                                 'receipt':receipt,'outputs_origin':'supplied_samples','model_called':False})
    rows=[{'input':s.input_text,'expected':s.expected} for s in suite.scenarios]
    dataset=split_rows(rows,test_percent=request['split']['test_percent'])
    by_input={}
    for row in dataset['items']:
        if row['input'] in by_input:raise OpsValidationError('same input has conflicting expected values; split refused')
        by_input[row['input']]=row['id']
    mapping={row['id']:[] for row in dataset['items']}
    for scenario in suite.scenarios:mapping[by_input[scenario.input_text]].append(scenario.scenario_id)
    assigned=[{'pair_sha256':row['id'],'split':row['split'],'scenario_ids':sorted(mapping[row['id']])} for row in dataset['items']]
    extra={'split.json':{'schema':'promptops-split/1','algorithm':ALGORITHM,'test_percent':request['split']['test_percent'],
             'evaluation_scope':'complete_replay_suite','holdout_evaluation_executed':False,'training_executed':False,
             'suite_sha':suite.suite_sha,'source_rows':len(rows),'unique_rows':len(assigned),'duplicates_removed':len(rows)-len(assigned),
             'source_dataset_sha256':dataset['sha256'],'partitions':assigned,
             'train_count':sum(x['split']=='train' for x in assigned),'test_count':sum(x['split']=='test' for x in assigned)},
           'packages.json':{'schema':'promptops-package-tests/1','suite_sha':suite.suite_sha,'candidate_tests':package_receipts,
                            'installed':False,'published':False,'provider_called':False}}
    extra['split.json']['partition_status']='both_nonempty' if extra['split.json']['train_count'] and extra['split.json']['test_count'] else 'single_nonempty'
    evidence=[values['dataset.json'],values['scorecard.json']]
    regressions=[values['regression.json']] if 'regression.json' in values else []
    release=release_manifest(release_version=request['release_version'],dataset=evidence[0],scorecards=[evidence[1]],regressions=regressions)
    release_receipt=verify_release_bundle(release,[*evidence,*regressions])
    extra['release.json']=release
    hashes={name:hashlib.sha256(encode(value)).hexdigest() for name,value in {**values,**extra}.items()}
    provenance=request['provenance']
    declared_record=None
    if provenance['duration_ms'] is not None:
        declared_record=record_benchmark({'benchmark':suite.suite_id,'configuration':{'suite_sha':suite.suite_sha},
            'duration_ms':provenance['duration_ms'],'result':{'replay_candidates':len(suite.candidates),'replay_scenarios':len(suite.scenarios)},
            'artifacts':[{'path':name,'sha256':digest} for name,digest in sorted(hashes.items())]})
    extra['metrics-origin.json']={'schema':'promptops-metrics-origin/1','suite_sha':suite.suite_sha,'report_sha':result['report_sha'],
         'latency_origin':'supplied_replay_samples','cost_origin':'calculated_from_supplied_tokens_and_candidate_prices',
         'independent_measurement':False,'provenance_verified':False,'provider_called':False,
         'declaration':dict(provenance),'declared_at_status':'absent' if provenance['declared_at'] is None else 'declared_not_observed',
         'duration_status':'not_supplied' if declared_record is None else 'declared_not_measured','benchmark_record':declared_record}
    hashes['metrics-origin.json']=hashlib.sha256(encode(extra['metrics-origin.json'])).hexdigest()
    extra['bundle.json']={'schema':'promptops-workflow-bundle/1','request_sha256':hashlib.sha256(encode(request)).hexdigest(),
         'suite_sha':suite.suite_sha,'report_sha':result['report_sha'],'artifacts':hashes,'release_verification':release_receipt,
         'decision':result['decision'],'gate_passed':result['gate_passed'],'provider_called':False,'provenance':'not-verified',
         'holdout_evaluation_executed':False,'sensitive_pattern_policy':'best-effort-refusal-before-export-v1'}
    if sum(len(encode(x)) for x in [*values.values(),*extra.values()])>MAX_EXPORT:
        raise OpsValidationError('bundle export byte budget exceeded')
    return extra
